In [167]:
import os
import numpy as np 
import pandas as pd


In [168]:
os.getcwd()

'C:\\Users\\jhard\\Downloads'

In [169]:
os.chdir('C:\\Users\\jhard\\Downloads')

In [170]:
messy_data = pd.read_csv('dirty_financial_transactions.csv')

In [171]:
messy_data.head()

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
0,T0001,2024-08-02,C2205,Headphones,-5.0,$420.21,pay pal,NaN
1,T0002,2020-02-10,C3156,Coffee,469.0,-445.34202525395585,creditcard,Pending
2,T0003,2025-02-30,C2919,Tablet,-4.0,810.9930123946459,credit card,completed
3,T0004,2020-08-17,C3009,Tab,-7.0,868.6083413217348,PayPal,Pending
4,T0005,2025-02-30,C3488,Coffee Machine,-10.0,-763.1224490039416,PayPal,completed


In [172]:
print('total no of rows in this Dataset -', messy_data.shape[0])

total no of rows in this Dataset - 100000


In [173]:
print('total no of Columns in this Dataset -', messy_data.shape[1])

total no of Columns in this Dataset - 8


In [174]:
messy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   Transaction_ID      94982 non-null   object 
 1   Transaction_Date    95120 non-null   object 
 2   Customer_ID         95122 non-null   object 
 3   Product_Name        100000 non-null  object 
 4   Quantity            94981 non-null   float64
 5   Price               66503 non-null   object 
 6   Payment_Method      100000 non-null  object 
 7   Transaction_Status  83321 non-null   object 
dtypes: float64(1), object(7)
memory usage: 6.1+ MB


Price, Quantity and Transaction Data has Wrong Data Types


In [175]:
messy_data.isnull().sum()/len(messy_data)*100

Transaction_ID         5.018
Transaction_Date       4.880
Customer_ID            4.878
Product_Name           0.000
Quantity               5.019
Price                 33.497
Payment_Method         0.000
Transaction_Status    16.679
dtype: float64

Identify how many duplicated Rows are present in Dataset

In [176]:
print('Total No of Duplicates Rows in Dataset', messy_data[messy_data.duplicated()].shape[0])

Total No of Duplicates Rows in Dataset 994


In [177]:
messy_data['Customer_ID'].value_counts()

Customer_ID
C4347    37
C2023    37
C4418    36
C876     36
C1955    35
         ..
C3782     7
C3324     7
C1635     7
C945      6
C1384     5
Name: count, Length: 5000, dtype: int64

So There are some Customers Who have Multiple rows in Dataset

So We will check that these rows are same or different

In [178]:
messy_data[messy_data['Customer_ID'] == 'C4347']

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
538,T0539,2023-13-01,C4347,Headphones,-7.0,NaN,PayPal,completed
642,T0643,2021-04-09,C4347,Laptop,-4.0,841.2991021061262,Cash,Failed
8934,T8935,2023-01-31,C4347,Coffee Machine,8.0,$-574.76,PayPal,Pending
12693,T12694,2023-13-01,C4347,Laptop,-10.0,-446.3360641696613,credit card,Failed
13670,T13671,2023-13-01,C4347,Headphones,923.0,$998.79,Credit Card,Completed
16148,T16149,2023-13-01,C4347,Headphones,9.0,NaN,credit card,complete
19422,T19423,2024-11-29,C4347,Headphones,NaN,-721.7148471235098,PayPal,Pending
22006,T22007,2025-02-30,C4347,Laptop,943.0,-464.77374826930225,PayPal,completed
23963,T23964,2023-10-14,C4347,Tablet,-6.0,63.78126911461825,Cash,Failed
24496,T24497,2020-05-09,C4347,Coffee Machine,439.0,845.894271048739,Credit Card,NaN


So Each Rows is Different 

Now we identity problem in Columns Name

In [179]:
for col in messy_data.columns:
  if messy_data[col].nunique() < 50:
    print(messy_data[col].value_counts())
    print('-'*50)

Product_Name
Tablet            18444
Laptop            18264
Smartphone        18257
Headphones        18107
Coffee Machine    18085
Lapt                370
Table               352
La                  347
Tabl                346
Lapto               344
Ta                  344
T                   335
Lap                 334
Tab                 330
L                   321
Smartph             234
S                   223
H                   217
He                  212
Smart               206
Head                204
Headpho             203
Smartphon           203
Headphon            203
Smartp              203
Headphone           202
Headp               201
Headph              193
Hea                 192
Sma                 191
Sm                  189
Smartpho            181
Smar                180
Coffee Ma           157
Coffee Machin       150
Coffee Machi        150
Coffee Mach         149
Coffee              149
C                   141
Coffee M            140
Cof                 137
Cof

In [180]:
messy_data['Price'].sort_values().unique()

# In Price Column, There is '$' sign and some null values

array(['$-100.57', '$-100.87', '$-100.96', ..., '999.9851066256931',
       '999.9876977023494', nan], shape=(65758,), dtype=object)

Till now We Focus on Identify Problems in this messy Dataset.

In [181]:
# Dropping Duplicated Values

messy_data.drop_duplicates(inplace=True)

In [182]:
# Checking duplicates values again

messy_data[messy_data.duplicated()]

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status


In [183]:
# dropping rows where customer id is null

messy_data.dropna(subset=['Customer_ID'], inplace=True)

In [184]:
messy_data.isnull().sum()/len(messy_data)*100

Transaction_ID         5.026758
Transaction_Date       4.871730
Customer_ID            0.000000
Product_Name           0.000000
Quantity               5.019326
Price                 33.468187
Payment_Method         0.000000
Transaction_Status    16.661357
dtype: float64

In [185]:
# generating transacation id for null values

# Total rows count karein
n = len(messy_data)

# Nayi IDs generate karein (T00001 format mein)
messy_data['Transaction_ID'] = [f'T{str(i+1).zfill(5)}' for i in range(n)]

In [186]:
messy_data.isnull().sum()/len(messy_data)*100

Transaction_ID         0.000000
Transaction_Date       4.871730
Customer_ID            0.000000
Product_Name           0.000000
Quantity               5.019326
Price                 33.468187
Payment_Method         0.000000
Transaction_Status    16.661357
dtype: float64

In [187]:
# changing price data types and working on null values and '$'

messy_data['Price'].str.startswith('$').value_counts()

Price
False    56416
True      6241
Name: count, dtype: int64

In [188]:
messy_data["Price"] = messy_data['Price'].str.replace('$', '', regex=False)

In [189]:
messy_data['Price'].sort_values().unique()

array(['-100.1120385623841', '-100.12379265881964', '-100.15344745799246',
       ..., '999.9851066256931', '999.9876977023494', nan],
      shape=(62550,), dtype=object)

In [190]:
messy_data['Price'] = messy_data['Price'].astype(float)

In [191]:
messy_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 94176 entries, 0 to 99998
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Transaction_ID      94176 non-null  object 
 1   Transaction_Date    89588 non-null  object 
 2   Customer_ID         94176 non-null  object 
 3   Product_Name        94176 non-null  object 
 4   Quantity            89449 non-null  float64
 5   Price               62657 non-null  float64
 6   Payment_Method      94176 non-null  object 
 7   Transaction_Status  78485 non-null  object 
dtypes: float64(2), object(6)
memory usage: 6.5+ MB


In [192]:
messy_data['Price'].sort_values().unique()

array([-999.96890297, -999.94363099, -999.91582127, ...,  999.98510663,
        999.9876977 ,           nan], shape=(62550,))

In [193]:
messy_data['Price'] = messy_data['Price'].fillna(messy_data['Price'].median())

In [194]:
messy_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 94176 entries, 0 to 99998
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Transaction_ID      94176 non-null  object 
 1   Transaction_Date    89588 non-null  object 
 2   Customer_ID         94176 non-null  object 
 3   Product_Name        94176 non-null  object 
 4   Quantity            89449 non-null  float64
 5   Price               94176 non-null  float64
 6   Payment_Method      94176 non-null  object 
 7   Transaction_Status  78485 non-null  object 
dtypes: float64(2), object(6)
memory usage: 6.5+ MB


In [195]:
# working in Quantity Columns

In [196]:
messy_data['Quantity'].sort_values().unique()

array([ -10.,   -9.,   -8.,   -7.,   -6.,   -5.,   -4.,   -3.,   -2.,
         -1.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
          9.,   10.,  100.,  101.,  102.,  103.,  104.,  105.,  106.,
        107.,  108.,  109.,  110.,  111.,  112.,  113.,  114.,  115.,
        116.,  117.,  118.,  119.,  120.,  121.,  122.,  123.,  124.,
        125.,  126.,  127.,  128.,  129.,  130.,  131.,  132.,  133.,
        134.,  135.,  136.,  137.,  138.,  139.,  140.,  141.,  142.,
        143.,  144.,  145.,  146.,  147.,  148.,  149.,  150.,  151.,
        152.,  153.,  154.,  155.,  156.,  157.,  158.,  159.,  160.,
        161.,  162.,  163.,  164.,  165.,  166.,  167.,  168.,  169.,
        170.,  171.,  172.,  173.,  174.,  175.,  176.,  177.,  178.,
        179.,  180.,  181.,  182.,  183.,  184.,  185.,  186.,  187.,
        188.,  189.,  190.,  191.,  192.,  193.,  194.,  195.,  196.,
        197.,  198.,  199.,  200.,  201.,  202.,  203.,  204.,  205.,
        206.,  207.,

In [197]:
messy_data['Quantity'] = messy_data['Quantity'].fillna(messy_data['Quantity'].median())

In [198]:
messy_data['Quantity'].sort_values().unique()

array([ -10.,   -9.,   -8.,   -7.,   -6.,   -5.,   -4.,   -3.,   -2.,
         -1.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
          9.,   10.,  100.,  101.,  102.,  103.,  104.,  105.,  106.,
        107.,  108.,  109.,  110.,  111.,  112.,  113.,  114.,  115.,
        116.,  117.,  118.,  119.,  120.,  121.,  122.,  123.,  124.,
        125.,  126.,  127.,  128.,  129.,  130.,  131.,  132.,  133.,
        134.,  135.,  136.,  137.,  138.,  139.,  140.,  141.,  142.,
        143.,  144.,  145.,  146.,  147.,  148.,  149.,  150.,  151.,
        152.,  153.,  154.,  155.,  156.,  157.,  158.,  159.,  160.,
        161.,  162.,  163.,  164.,  165.,  166.,  167.,  168.,  169.,
        170.,  171.,  172.,  173.,  174.,  175.,  176.,  177.,  178.,
        179.,  180.,  181.,  182.,  183.,  184.,  185.,  186.,  187.,
        188.,  189.,  190.,  191.,  192.,  193.,  194.,  195.,  196.,
        197.,  198.,  199.,  200.,  201.,  202.,  203.,  204.,  205.,
        206.,  207.,

In [199]:
messy_data['Quantity'] = messy_data['Quantity'].astype(int)

In [200]:
messy_data['Quantity'] = messy_data['Quantity'].apply(lambda x: x if x >= 0 else 0 )

In [201]:
messy_data['Quantity'].sort_values().unique()

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  151,  152,  153,  154,
        155,  156,  157,  158,  159,  160,  161,  162,  163,  164,  165,
        166,  167,  168,  169,  170,  171,  172,  173,  174,  175,  176,
        177,  178,  179,  180,  181,  182,  183,  184,  185,  186,  187,
        188,  189,  190,  191,  192,  193,  194,  195,  196,  197,  198,
        199,  200,  201,  202,  203,  204,  205,  206,  207,  208,  209,
        210,  211,  212,  213,  214,  215,  216,  217,  218,  219,  220,
        221,  222,  223,  224,  225,  226,  227,  228,  229,  230,  231,
        232,  233,  234,  235,  236,  237,  238,  2

In [202]:
messy_data['Transaction_Status'] = messy_data['Transaction_Status'].fillna('completed')

In [203]:
messy_data['Transaction_Status'].unique()

array(['completed', 'Pending', 'Completed', 'complete', 'Failed'],
      dtype=object)

In [204]:
messy_data['Transaction_Status'] = messy_data['Transaction_Status'].replace({'completed': 'Completed',
                                                                            'complete': 'Completed'})

In [205]:
messy_data['Transaction_Status'].unique()

array(['Completed', 'Pending', 'Failed'], dtype=object)

In [206]:
messy_data['Payment_Method'].unique()

array(['pay pal', 'creditcard', 'credit card', 'PayPal', 'Cash',
       'PayPal ', 'Credit Card'], dtype=object)

In [207]:
messy_data['Payment_Method'] = messy_data['Payment_Method'].replace({'pay pal': 'Paypal', 'PayPal ': 'Paypal',
                                                                    'creditcard': 'CreditCard', 'credit card': 'CreditCard' })

In [208]:
messy_data['Payment_Method'] = messy_data['Payment_Method'].replace({'Paypal': 'PayPal'})

In [209]:
messy_data['Payment_Method'] = messy_data['Payment_Method'].replace({'Credit Card': 'CreditCard'})

In [210]:
messy_data['Payment_Method'].unique()

array(['PayPal', 'CreditCard', 'Cash'], dtype=object)

In [211]:
messy_data['Product_Name'].unique()

array(['Headphones', 'Coffee ', 'Tablet', 'Tab', 'Coffee Machine',
       'Smartphone', 'Laptop', 'Coffee Ma', 'Cof', 'Smar', 'Coffee M',
       'T', 'Smartp', 'Headp', 'Smart', 'La', 'Lapt', 'Tabl', 'L', 'C',
       'Smartph', 'Hea', 'Head', 'Smartpho', 'Lapto', 'Headphon', 'Table',
       'Headphone', 'Coffee Mac', 'Sm', 'Coffee', 'Headph', 'S',
       'Coffee Mach', 'Smartphon', 'Headpho', 'Coffee Machin', 'Coff',
       'Co', 'Lap', 'H', 'He', 'Ta', 'Coffee Machi', 'Coffe', 'Sma'],
      dtype=object)

In [212]:
messy_data['Product_Name'] = messy_data['Product_Name'].str.lower()

In [213]:
messy_data['Product_Name'] = messy_data['Product_Name'].apply(lambda x: 'coffee' if x.startswith('c') else
                                                             'headphones' if x.startswith('h') else 
                                                              'laptop' if x.startswith('l') else
                                                              'smartphone' if x.startswith('s') else
                                                              'other')

In [214]:
messy_data['Product_Name'].unique()

array(['headphones', 'coffee', 'other', 'smartphone', 'laptop'],
      dtype=object)

In [221]:
messy_data['Transaction_Date'] = pd.to_datetime(messy_data['Transaction_Date'], errors='coerce')

In [224]:
messy_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 94176 entries, 0 to 99998
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Transaction_ID      94176 non-null  object        
 1   Transaction_Date    29922 non-null  datetime64[ns]
 2   Customer_ID         94176 non-null  object        
 3   Product_Name        94176 non-null  object        
 4   Quantity            94176 non-null  int64         
 5   Price               94176 non-null  float64       
 6   Payment_Method      94176 non-null  object        
 7   Transaction_Status  94176 non-null  object        
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 6.5+ MB


In [222]:
clean_data = messy_data

In [223]:
clean_data

,Transaction_ID,Transaction_Date,Customer_ID,Product_Name,Quantity,Price,Payment_Method,Transaction_Status
0,T00001,2024-08-02,C2205,headphones,0,420.210000,PayPal,Completed
1,T00002,2020-02-10,C3156,coffee,469,-445.342025,CreditCard,Pending
2,T00003,NaT,C2919,other,0,810.993012,CreditCard,Completed
3,T00004,2020-08-17,C3009,other,0,868.608341,PayPal,Pending
4,T00005,NaT,C3488,coffee,0,-763.122449,PayPal,Completed
...,...,...,...,...,...,...,...,...
99994,T94172,NaT,C2153,smartphone,741,52.005263,PayPal,Completed
99995,T94173,2021-10-06,C1743,headphones,0,240.003238,PayPal,Completed
99996,T94174,2024-08-25,C4830,smartphone,6,503.829517,CreditCard,Completed
99997,T94175,NaT,C280,laptop,0,52.005263,PayPal,Completed
